apiVersion: apps/v1
kind: Deployment
metadata:
  name: sfs-app
  labels:
    app: sfs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sfs-app
  template:
    metadata:
      labels:
        app: sfs-app
    spec:
      containers:
      - name: sfs-app
        image: hemanth0914/cicd-e2e:replaceImageTag
        ports:
        - containerPort: 8000